In [1]:
import requests

In [2]:
import pandas as pd

In [7]:
df=pd.read_csv('muhammet_data.csv',sep=';')  #noktalı virgül olan yerlerden datayı düzenledim

In [8]:
df.head()


subjno             isim  grup  tanı  yas  cins  gelsekil  meddur  isdurum  \
0      77       kamer sarı     1     1   46     1         1       3        1   
1      75       özlem sarı     2     0   41     1         1       3        2   
2      74  alperen erdoğan     2     0   30     2         1       2        1   
3      79       amine sarı     2     0   50     1         1       3        1   
4      78      serpil sarı     2     0   40     1         1       1        1   

   egitim  ...  novseek  harmavo  rewdep  persist  selfdirect  cooper  \
0      17  ...       11       20      10        4          35      30   
1      15  ...       11       25       9        3          33      33   
2      18  ...       22       21      17        2          25      32   
3      13  ...       14       25      16        5          34      34   
4      16  ...       17        5      17        7          37      22   

  selftrans des_kategor  disq_kategor  filter_$  
0         9           1             1         1  
1         5           1             1         0  
2         3           1             1         0  
3        15           1             1         0  
4        15           1             1         0  

[5 rows x 28 columns]

In [11]:
df.iloc[10]

subjno                   2
isim            huriye öen
grup                     2
tanı                     0
yas                     52
cins                     1
gelsekil                 1
meddur                   1
isdurum                  1
egitim                  21
ekondur                  2
tedavi                   1
hastsur                  0
alkolmadde               1
hama                     4
hamd                     2
des                   3,92
disq                  1,23
novseek                 18
harmavo                  9
rewdep                  14
persist                  8
selfdirect              30
cooper                  30
selftrans               15
des_kategor              1
disq_kategor             1
filter_$                 0
Name: 10, dtype: object

In [12]:
df['isim']

0           kamer sarı
1           özlem sarı
2      alperen erdoğan
3           amine sarı
4          serpil sarı
            ...       
145        nuriye acar
146          hasta 110
147          hasta 111
148          hasta 121
149          hasta 142
Name: isim, Length: 150, dtype: object

In [14]:
for bought ,group in df.groupby('grup'):
    print(bought)
    print(group)

1
     subjno           isim  grup  tanı  yas  cins  gelsekil  meddur  isdurum  \
0        77     kamer sarı     1     1   46     1         1       3        1   
44       28    gizem güler     1     1   21     1         1       2        3   
45       29  mustafa doğan     1     1   23     2         1       2        2   
46       30    rabia bulut     1     2   38     1         1       1        1   
47       31    gamze şener     1     1   24     1         1       1        2   
..      ...            ...   ...   ...  ...   ...       ...     ...      ...   
145      93    nuriye acar     1     1   40     1         1       1        1   
146     110      hasta 110     1     1   21     1         1       2        3   
147     111      hasta 111     1     1   21     2         1       2        3   
148     121      hasta 121     1     2   22     2         1       2        3   
149     142      hasta 142     1     2   35     2         1       1        1   

     egitim  ...  novseek  harmavo  r

In [16]:
pd :pivot_table?


Object `pivot_table` not found.


In [ ]:
pd :pivot_table

In [18]:
pd.pivot_table?


In [ ]:
pd.pivot_table(df2,values=['selftrans'],colum)

In [19]:
df.describe()

subjno        grup        tanı         yas        cins    gelsekil  \
count  150.000000  150.000000  150.000000  150.000000  150.000000  150.000000   
mean    75.500000    1.500000    0.700000   30.386667    1.400000    1.013333   
std     43.445368    0.501675    0.783641   10.528189    0.491539    0.115082   
min      1.000000    1.000000    0.000000   18.000000    1.000000    1.000000   
25%     38.250000    1.000000    0.000000   23.000000    1.000000    1.000000   
50%     75.500000    1.500000    0.500000   26.500000    1.000000    1.000000   
75%    112.750000    2.000000    1.000000   36.000000    2.000000    1.000000   
max    150.000000    2.000000    2.000000   63.000000    2.000000    2.000000   

           meddur     isdurum      egitim     ekondur  ...     novseek  \
count  150.000000  150.000000  150.000000  150.000000  ...  150.000000   
mean     1.640000    2.040000   13.826667    2.180000  ...   18.346667   
std      0.570882    0.842495    4.319064    0.449758  ...    5.127877   
min      1.000000    1.000000    4.000000    1.000000  ...    5.000000   
25%      1.000000    1.000000   12.000000    2.000000  ...   14.000000   
50%      2.000000    2.000000   14.000000    2.000000  ...   18.000000   
75%      2.000000    3.000000   17.000000    2.000000  ...   22.000000   
max      3.000000    3.000000   22.000000    3.000000  ...   33.000000   

          harmavo     rewdep     persist  selfdirect      cooper   selftrans  \
count  150.000000  150.00000  150.000000  150.000000  150.000000  150.000000   
mean    21.473333   13.86000    4.653333   27.666667   28.293333   15.540000   
std      6.306167    3.35991    1.741660    7.815547    6.137733    5.794733   
min      5.000000    7.00000    0.000000    8.000000   12.000000    2.000000   
25%     17.000000   11.00000    3.250000   21.000000   24.000000   12.000000   
50%     22.000000   14.00000    5.000000   29.000000   28.500000   15.500000   
75%     26.000000   16.00000    6.000000   34.000000   33.000000   19.000000   
max     34.000000   22.00000    8.000000   44.000000   40.000000   30.000000   

       des_kategor  disq_kategor    filter_$  
count   150.000000    150.000000  150.000000  
mean      1.126667      1.160000    0.500000  
std       0.333713      0.367834    0.501675  
min       1.000000      1.000000    0.000000  
25%       1.000000      1.000000    0.000000  
50%       1.000000      1.000000    0.500000  
75%       1.000000      1.000000    1.000000  
max       2.000000      2.000000    1.000000  

[8 rows x 25 columns]

In [21]:
list(map(lambda x:x+1 ,[1,2,3,4])) #map  burada birer lambda fonksiyonunu uygular, fonksiyonel bir özelliktir

[2, 3, 4, 5]

In [23]:
list(filter(lambda x:x%7==0,list(range(71)))) #if gibi çalışır lambda fonksiyonundaki true olan yerleri yazar

[0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 70]

In [24]:
reduce(lambda a,b:a*b,[2,3,4,5])      #python2 de kullanılıyor

NameError: name 'reduce' is not defined

In [28]:
l=[1,2,3,4,3,1]

In [32]:
l.sort()     # işlemi verinin bulundugu yerde gerçekleştirdi bu yüzden veri degişti ,inline=kopyasını ürtmeden datanın içinde işlem yapma

In [33]:
sorted(l)  #l ye atamadı

[1, 1, 2, 3, 3, 4]

In [34]:
l

[1, 1, 2, 3, 3, 4]

In [35]:
df.apply??

In [36]:
a=[[2018,5,24],[2018,10,10],[2019,10,24],[2018,3,24],[2018,10,4],[7,10,24],[2018,10,4]]

In [39]:
import numpy as np


In [41]:
data = np.array([['','Col1','Col2'],
                ['Row1',2018,2],
                ['Row2',2018,3],
                ['Row1',2018,4],
                ['Row1',2018,5],
                ['Row1',2018,6],
                ['Row1',2018,7],
                ['Row1',2018,8],])

In [42]:
data=pd.DataFrame(data=data[1:,1:],
                  index=data[1:,0],
                  columns=data[0,1:])

In [43]:
data


Col1 Col2
Row1  2018    2
Row2  2018    3
Row1  2018    4
Row1  2018    5
Row1  2018    6
Row1  2018    7
Row1  2018    8

In [51]:
data.rename(index={'Col1':'Year','Col2':'Mounth'})

Col1 Col2
Row1  2018    2
Row2  2018    3
Row1  2018    4
Row1  2018    5
Row1  2018    6
Row1  2018    7
Row1  2018    8

In [53]:
l=[1,2,3,4]
k=[4,5,6,7]
k+l

[4, 5, 6, 7, 1, 2, 3, 4]

In [54]:
import numpy as np

In [58]:
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
a+b

array([ 5,  7,  9, 11])

In [59]:
type(a)

numpy.ndarray

In [67]:
array2d1=np.array([
 [1,2,3],
 [2,3,4]  
    
])

In [68]:
array2d1

array([[1, 2, 3],
       [2, 3, 4]])

In [71]:
array2d2=np.array([
 [4,5],
 [7,8],
 [8,9]
    
])

In [72]:
np.matmul(array2d1,array2d2)

array([[42, 48],
       [61, 70]])

In [73]:
array2d1@array2d2

array([[42, 48],
       [61, 70]])

In [74]:
array2d1.shape 

(2, 3)

In [75]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [77]:
np.ones((3))

array([1., 1., 1.])

In [83]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [90]:
sarray=np.array([
    [1,15,3],
    [20,3,4],
    [3,4,18]
])

In [91]:
np.linalg.inv(sarray) @sarray

array([[ 1.00000000e+00,  1.38777878e-17,  1.38777878e-17],
       [ 1.73472348e-18,  1.00000000e+00,  1.04083409e-17],
       [-6.93889390e-18,  0.00000000e+00,  1.00000000e+00]])

In [92]:
np.linalg.matrix_power(sarray,3)

array([[2101, 5334, 3324],
       [7024, 2931, 4168],
       [3764, 3838, 7209]])

In [94]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [96]:
np.random.randint(1,1000,10).reshape((2,5))

array([[791, 510, 163, 136, 346],
       [622, 535, 730, 521, 548]])

In [98]:
l=np.array(l)

In [99]:
l

array([1, 2, 3, 4])

In [100]:
sarray.reshape(1,-1)

array([[ 1, 15,  3, 20,  3,  4,  3,  4, 18]])

In [101]:
sarray.reshape(-1,1)

array([[ 1],
       [15],
       [ 3],
       [20],
       [ 3],
       [ 4],
       [ 3],
       [ 4],
       [18]])

In [102]:
sarray.T

array([[ 1, 20,  3],
       [15,  3,  4],
       [ 3,  4, 18]])

In [103]:
sarray

array([[ 1, 15,  3],
       [20,  3,  4],
       [ 3,  4, 18]])

In [104]:
np.transpose(sarray)

array([[ 1, 20,  3],
       [15,  3,  4],
       [ 3,  4, 18]])

In [105]:
sarray[1,2]

4

In [107]:
sarray[1:3,0:2]

array([[20,  3],
       [ 3,  4]])

In [1]:
import numpy as np

In [2]:
np.arange(3)-1

array([-1,  0,  1])